### ISSUE TITLE
Folders not loading.

### ISSUE THREAD

**Issue by jpronans** [bitwarden/desktop#1011]
## Describe the Bug

Bitwarden never loads/shows the folders that should appear below "Secure Note"

## Steps To Reproduce

Start the client and log in with passphrase

## Expected Result

Folders display as normal

## Actual Result

They never appear, 

## Screenshots or Videos

![Screenshot from 2021-08-03 18-15-06](https://user-images.githubusercontent.com/650774/128058243-7e381764-b150-4421-8d54-463b44b40677.png)

## Environment
PopOs 20.04 
Bitwarden Snap version 1.27.1  Rev   52
Version 1.27.1
Shell 11.4.5
Renderer 87.0.4280.141
Node 12.18.3
Arch X64

## Additional Context

Searching for items and putting items into folders still works.

**Comment by eliykat** [comment]
Hi @jpronans, I think this is a duplicate of one of the following issues:
* corrupted `data.json` from an earlier install (pre-1.26.4). Try exiting Bitwarden, deleting your local data ([here](https://bitwarden.com/help/article/data-storage/) is a list of local data locations) and then opening Bitwarden again. You're already on a later version, so you shouldn't need to reinstall, but it might help anyway if the problem is persisting.
* there was an ArchLinux user in the comments here who had some problems with infinite loading: https://github.com/bitwarden/desktop/issues/760. Your issue looks a little different, but Arch jumped out at me.

**Comment by jpronans** [comment]
Thanks.
So, just deleting the ~/snap/bitwarden/current/.config/Bitwarden wasn't enough. I uninstalled the snap, removed ~/snap/bitwarden re-installed and all is well again. FWIW There was a dangling link left in the bitwarden directory.Thanks.
