### ISSUE TITLE
Hide menu bar on Linux

### ISSUE THREAD

**Issue by julianfairfax** [bitwarden/desktop#1013]
## Steps To Reproduce

1. Open the app
2. See a menu bar where one shouldn't be

## Expected Result

No menu bar

## Actual Result

A menu bar

## Screenshots or Videos

There is a menu bar:
![image](https://user-images.githubusercontent.com/43753131/128256774-54a1e288-77f3-45b3-b79e-ea86df60726b.png)

## Environment

- Operating system: Linux
- Installation method: Downloaded from Bitwarden.com
- Build Version (go to "Settings" → "About"): 1.7.1

## Additional Context

No

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

If I've misunderstood and this is actually a bug, please let me know.

This issue will now be closed. Thanks!

**Comment by julianfairfax** [comment]
Well, its not a bug but it is a discrepancy with the Linux app compared to the macOS and Windows apps.
