### ISSUE TITLE
macOS universal pkg is x86_64 only

### ISSUE THREAD

**Issue by ghost** [bitwarden/desktop#1046]
## Describe the Bug

The macOS universal pkg is `x86_64` only and doesn't work on a `arm64` system without Rosetta 2

## Steps To Reproduce

Download `Bitwarden-1.28.1-universal.pkg` from GitHub and open it without Rosetta 2 installed

## Expected Result

Rosetta 2 is not needed to install the universal pkg on a `arm64` system

## Actual Result

Dialog appears: 

> To open "Bitwarden", you need to install Rosetta. Do you want to install it now? [..] 

Cancel this dialog quits install process.

## Environment

- Operating system: Big Sur 11.5.2
- Installation method: GitHub
- Build Version (go to "Settings" → "About"): 1.28.1

## Additional Context

The `Distribution` file within the pkg says `hostArchitectures="x86_64"` instead of `hostArchitectures="x86_64,arm64"`.

**Comment by eliykat** [comment]
We currently do not provide a native arm64 build. We tried to add this in https://github.com/bitwarden/desktop/pull/1095, however it was not compatible with our build pipelines and had to be reverted. It's on our DevOps roadmap.

In the meantime, this is a feature request. We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
