### ISSUE TITLE
Searching with the desktop version

### ISSUE THREAD

**Issue by RichardSypriano** [bitwarden/desktop#1055]
## Describe the Bug

In the Desktop version the Search control at the top of the screen only finds items in the current folder. It should, in my opinion find all occurrences in all folders.

## Steps To Reproduce

1. Create a folder
2. Move a know item to the new folder 
3. Select any other folder other than the one you just created
4. In the search bar at the top of the screen type in the name of the item you moved to the new folder
5. No results are shown 

## Expected Result

I expect to see the item I moved

## Actual Result

No results are shown 

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/39841721/131854597-8f989ecb-a15d-4d11-8838-d8107a3de9b1.png)

## Environment

Windows 10
Downloaded from Bitwarden.com
1.28.2

**Comment by Greenderella** [comment]
Hi @RichardSypriano 

You need to select the option "All items" and then type your search term if you want for the search to be performed in all your items/folders:

![1](https://user-images.githubusercontent.com/5418577/131868608-b6271448-0621-4f77-979c-d90da0783a72.png)

**Comment by eliykat** [comment]
I'm closing this because it's not an actionable defect, but if you have any other questions you can:
* contact our Customer Success team here: https://bitwarden.com/contact. 
* search for an answer in our [help documentation](https://bitwarden.com/help/) 
* get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/).
