### ISSUE TITLE
Windows Taskbar Icon

### ISSUE THREAD

**Issue by parthe** [bitwarden/desktop#1057]
Icon is wrong/incomplete in the taskbar for windows.

![image](https://user-images.githubusercontent.com/5085600/131976497-57ae0029-5056-440c-a6c8-6d02ee63e8c0.png)

How can we reproduce the behavior:

1. Open Bitwarden on Windows
2. Right-click on the icon in the taskbar
3. Click Pin to taskbar
4. Restart Bitwarden

## Expected Result

An icon which is only the top-left part of the true icon of Bitwarden

## Environment info

- OS: Windows 10
- Installation method: [Downloaded from Bitwarden.com] 
- Build Version: [1.12.2]

**Comment by eliykat** [comment]
We've been unable to reproduce this bug using the instructions you've provided. Please contact our Customer Success team using our contact page, here: https://bitwarden.com/contact. They will help you troubleshoot the problem. If it can be reproduced as a defect, we'll reopen this issue for further attention.

You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
