### ISSUE TITLE
Unable to sync password change except on web page

### ISSUE THREAD

**Issue by bsthinker** [bitwarden/desktop#1063]
## Describe the Bug
Mac Desktop client
View -> Generate password
Manually updated password.  
Then File -> sync vault.
Message stated that sync was successful

Went to iPhone client and synced.  Password remained the original password.

Made a local copy of password and opened desktop client.  Original password present.

Did this multiple times bpth pn a pihole network ad on a network without pihole.

Only way to change through web client
  
Used the generate password feature 

## Steps To Reproduce

4. Click on '...'
Instructions lited earlier
## Expected Result

I expect to change my password in any client and have the vault be synced.
If that is not possible, I expect an error message to be issued stating that passwords can'f be updated from client.

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Installation method: [e.g. Downloaded from Bitwarden.com, Mac App Store / Microsoft Store, Homebrew, Snap] 
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
