### ISSUE TITLE
Ubuntu failed to fetch

### ISSUE THREAD

**Issue by LoSaMe** [bitwarden/desktop#1065]
_Originally posted by @LoSaMe in https://github.com/bitwarden/desktop/issues/514#issuecomment-915339724_

**Comment by eliykat** [comment]
Hi @LoSaMe, please don't create new issues just to boost a comment. We do our best to respond to comments on closed issues if the issue is still occurring for someone, or you can create a new issue with full reproduction information.

In this case, it looks like it may have been a configuration issue. Please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
