### ISSUE TITLE
Moving password in another folder crashes appImage

### ISSUE THREAD

**Issue by Barti-meaus** [bitwarden/desktop#107]
Hi :wave: 
I tried to move a password, via drag-and-drop, from one folder to another but the Desktop App freezes and in the terminal the following error occurs:

`Gtk-Message: 13:01:05.450: GtkDialog mapped without a transient parent. This is discouraged.`

Using: Bitwarden-1.3.0-x86_64.AppImage
System: Pop! OS 
```
$ cat /proc/version
Linux version 4.15.0-24-generic (buildd@lgw01-amd64-056) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018
```

**Comment by kspearrin** [comment]
Bitwarden does not have drag-n-drop support for folders.

**Comment by dangelion** [comment]
@kspearrin drag and drop would be a very useful feature for easily managing passwords. At today it's very slow selecting the folder for each passwords

**Comment by prediscover** [comment]
Drag and Drop for folders would be AMAZING!

**Comment by cscharf** [comment]
For drag and drop as a feature request, the [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
