### ISSUE TITLE
Bitwarden will allow you to close the application whilst editing or creating an item

### ISSUE THREAD

**Issue by ob14** [bitwarden/desktop#1078]
### Steps To Reproduce

1. Add a new item or edit an existing item
2. Change any information
3. Exit bitwarden

### Expected Result

A prompt should appear to confirm you wish to exit the application with unsaved changes.

### Actual Result

The application will exit, causing data loss.

### Operating System

Windows, macOS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.28.2

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
