### ISSUE TITLE
Mac Desktop version 1.28.2 frozen, can't click on anything

### ISSUE THREAD

**Issue by amossc** [bitwarden/desktop#1087]
### Steps To Reproduce

On Mac with OS 11.5.2:
1. Open Bitwarden desktop app on Mac
2. It doesn't respond to any click on the window
3. Quit via the "Bitwarden" app top bar menu - it quits
4. Try to start it - it doesn't start

I worked for a bit after the Mac reboot (after an OS update), but didn't accept thumbprint unlock from the Chrome extension. Then it stopped responding to any clicks on the window.

The Chrome extension seems to work fine.

### Expected Result

Respond to clicks on the MacOS desktop client.

### Actual Result

No response. Can't restart after quiting.

### Operating System

macOS

### Operating System Version

11.5.2

### Installation method

Mac App Store

### Build Version

1.28.2

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
