### ISSUE TITLE
Difficult to select individual item in vault to edit / view / copy

### ISSUE THREAD

**Issue by jim62146** [bitwarden/desktop#1114]
### Steps To Reproduce

1. Go to browser icon bar at top right
2. Click on shield icon
3. Move cursor to bottom row of window
4. Click on vault padlock
5. Move cursor to upper right scroll gadget on right edge of window
6. Click on gadget and drag to bottom of window

### Expected Result

View should go all the way to bottom of list.

### Actual Result

Scroll gadget "sticks" to window partway down. You continue "drag" action but gadget stays behind. If you move your cursor back onto the window the arrow cursor is replaced with the "index finger hand" cursor and the scroll gadget attaches to the vertical position of the "hand". If you move the cursor vertically the list entries "fly by" under the cursor. It is almost impossible to select one to click on.

### Operating System

Linux

### Operating System Version

Ubuntu Mate, both 21.04 and 21.10

### Installation method

Other

### Build Version

1.53.0 from extension store in Firefox 93.0

**Comment by eliykat** [comment]
Hi @jim62146, I'm not quite sure I understand the problem you're experiencing, but it sounds like it might be a bug. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
