### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID for self hosted vault

### ISSUE THREAD

**Issue by diiirt** [bitwarden/desktop#1125]
### Steps To Reproduce

1. Toggle developer tools
2. try to login

### Expected Result

login

### Actual Result

vendor.js:124065 POST https://www.bitwarden.local/api/accounts/prelogin net::ERR_CERT_AUTHORITY_INVALID
vendor.js:125625 01:59:29.596 › Received API exception: TypeError: Failed to fetch

### Additional Context

there should be some way to accept the self signed cert for local self hosted setups.  I tried adding custom root CA certificates but it didn't help.  The browser extension works fine though so it's not a huge deal.  

### Operating System

Linux

### Operating System Version

deb 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.29.0

**Comment by clayadams5226** [comment]
hey, @diiirt Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
