### ISSUE TITLE
Browser integration is not enabled

### ISSUE THREAD

**Issue by are-scenic** [bitwarden/desktop#1132]
### Steps To Reproduce

My system:
  Ubuntu 20.04.3 LTS
  Firefox 93.0 (64-bit), extension version 1.54.0
Information from Bitwarden desktop app:
  Version 1.29.0
  Shell 14.0.1
  Renderer 93.0.4577.63
  Node 14.17.0
  Architecture x64

I've installed the desktop app first and enabled the "Enable Browser Integration" option in its settings.
Then I've opened the Firefox browser and installed the Bitwarden extension. When I tried to enable "Unlock with biometrics", it failed and fired a message "Browser integration is not enabled", which is simply not true.

I've googled and also scanned to forums (including the official of Bitwarden, and I found this topic already flooding the network, but it stopped somewhere in the beginning of this year. It seems like it was solved, but for whatever reason it doesn't work on my PC.

### Expected Result

Expected the option to respond to the clicking

### Actual Result

Instead I get an error message "Enable Browser Integration"

### Screenshots or Videos

Related issue: https://github.com/bitwarden/browser/issues/1731
![Screenshot from 2021-10-29 16-36-41](https://user-images.githubusercontent.com/66092432/139463960-37e36463-d3cb-41a1-8146-f36b6dbcd118.png)

### Operating System

Linux

### Operating System Version

Ubuntu 20.04.3 LTS

### Installation method

Snap

### Build Version

Version 1.29.0

**Comment by gbcox** [comment]
Long story short, it's not supported yet on Linux.  I suggested they "grey out" the option on the desktop app in order to prevent confusion, since it doesn't appear it will be available anytime soon.  https://community.bitwarden.com/t/cant-enable-biometrics-for-chrome-or-edge-browser-extensions/26778/30?u=gbcox

**Comment by nicolasbrugneaux** [comment]
![image](https://user-images.githubusercontent.com/3650621/143688178-51c48bb1-1e42-4ce3-8434-2bff028b6e2f.png)

Same issue on windows 
```
Edition	Windows 11 Pro
Version	21H2
Installed on	‎02/‎11/‎2021
OS build	22000.318
Experience	Windows Feature Experience Pack 1000.22000.318.0
```

**Comment by eliykat** [comment]
@nicolasbrugneaux, this issue was related to Linux, which doesn't support biometrics. Windows does support it, so if you're encountering this error message, then it'll be a different problem. I recommend you contact our support team using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content.

In the meantime, I do think that we should disable this option on Linux given that it's not supported, so let's use this thread to track that issue.
