### ISSUE TITLE
missing TOTP code on logins from latest build/version

### ISSUE THREAD

**Issue by JessasaurusRida** [bitwarden/desktop#1140]
### Steps To Reproduce

any login that has Authenticator key (TOTP) setup on it

### Expected Result

![image](https://user-images.githubusercontent.com/10476614/140062853-b7230897-9339-4667-9d25-65b75117ad7e.png)

i should be seeing my 2FA code on image shown but i dont

### Actual Result

Can't login to any of my accounts that has 2FA enabled....

Can't copy/click on 2FA code 

![image](https://user-images.githubusercontent.com/10476614/140062820-83a82502-4b5e-42a2-8a91-9a7d95fc2613.png)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/10476614/140062820-83a82502-4b5e-42a2-8a91-9a7d95fc2613.png)

### Additional Context

issues on windows version/ edge and android versions

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Direct Download (from bitwarden.com), Microsoft Store

### Build Version

Version 1.29.1 Shell 14.0.1 Renderer 93.0.4577.63 Node 14.17.0 Architecture x64

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
