### ISSUE TITLE
Trouble logging in with the Desktop App

### ISSUE THREAD

**Issue by risingBirdSong** [bitwarden/desktop#1179]
### Steps To Reproduce

logging in with the Desktop App using Ubuntu I receive this error

An error has occurred.
An unexpected error has occurred.

logging in through the browser works. 

### Expected Result

Login in with the Desktop App

### Actual Result

An error has occurred.
An unexpected error has occurred.

### Operating System

Linux

### Operating System Version

Ubuntu 20.04.1 LTS 

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 1.27.1 Shell 11.4.5 Renderer 87.0.4280.141 Node 12.18.3 Architecture x64

**Comment by jonatanelgstrom** [comment]
I had this issue as well for the longest time .

Turned out to be an update that had gotten stuck.
See if you can update the app, alternatively install it again and then try to login .

hopefully this helps!

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
