### ISSUE TITLE
Typo error in the menu

### ISSUE THREAD

**Issue by damasoruiz** [bitwarden/desktop#1180]
### Steps To Reproduce

1. Click on 'the Menu -> Window
![bitwarden-menu-window-minimise](https://user-images.githubusercontent.com/59932918/144717047-b038e6de-5c44-4e31-80ad-1e4f1759003c.png)

### Expected Result

minimize

### Actual Result

minimise

### Screenshots or Videos

![bitwarden-menu-window-minimise](https://user-images.githubusercontent.com/59932918/144717139-b5267f9e-c283-454d-bdb3-fd0857127945.png)

### Operating System

Linux

### Operating System Version

kde-neon 5.23

### Installation method

Snap

### Build Version

1.29.1

**Comment by eliykat** [comment]
Hi @damasoruiz, please check your system region/language settings. This localisation (using s instead of z) only appears in the UK or India translation files. All other English localisations use the American "z".

If you update your system region/language and then restart Bitwarden, you should see your Bitwarden language updated accordingly.

If you need any further help with this, please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. Thank you!
