### ISSUE TITLE
Safari Extension gone

### ISSUE THREAD

**Issue by M-Whitaker** [bitwarden/desktop#1190]
### Steps To Reproduce

1. Go to Safari
2. Click on preferences 
3. Click on extensions
4. See there is no bitwarden extension

### Expected Result

Bitwarden safari extension is installed with the macOS app store distribution

### Actual Result

No bitwarden safari extension installed

### Additional Context

This seems to sometimes happen when the application updates. Maybe this needs to be looked into why it's not tested before release.

### Operating System

macOS

### Operating System Version

12.0.1

### Installation method

Mac App Store

### Build Version

Version 1.30.0 (1935) - arm64

**Comment by Hinton** [comment]
Hi @M-Whitaker,

We are unable to reproduce the issue. I suspect this is related to https://github.com/bitwarden/browser/issues/1696#issuecomment-874122595.

The macOS Launch Service has a tendency to sometimes end up in a corrupted state. This seems to happen regularly for some and never for others. Unfortunately since it's an OS level service, and App Store applications are sandboxed we don't really have any way of interacting with it.

The linked issue has multiple work-arounds which should assist in getting the extension back.
