### ISSUE TITLE
Cannot connect with Apple Watch when screen lid is down

### ISSUE THREAD

**Issue by rluvaton** [bitwarden/desktop#1344]
### Steps To Reproduce

1. Have an external display
1. Allow using biometrics in the app
1. Close the app
3. Close the lid
4. open the app and you don't see the _Unlock with Touch ID_ button that used to activate the Apple Watch login

### Expected Result

Even when the lid is closed I should use the Apple Watch to login

### Actual Result

There is no button for _Unlock with Touch ID_ (which allow unlocking the vault using the watch)

### Screenshots or Videos

When the lid is open, using _Unlock with Touch ID_ will let you use the Apple Watch to unlock:

![login-with-touch-id](https://user-images.githubusercontent.com/16746759/154047174-4d7d4298-cfe0-4892-8751-a746eb785c56.png)

When the lid is closed:
![login-when-lid-close](https://user-images.githubusercontent.com/16746759/154047451-52fcbc35-914f-465d-8a5e-8150e3b1daf6.png)

### Operating System

macOS

### Operating System Version

12.2.1

### Installation method

Mac App Store

### Build Version

1.30.0 (1935)

**Comment by Hinton** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
