### ISSUE TITLE
Unable to move item into collection using Desktop client

### ISSUE THREAD

**Issue by kvdb** [bitwarden/desktop#140]
I created a login account ('Item') visible under 'All Items'. I want to move this item into a collection. It seems there's no way of doing this. I read in another issue there's no drag&drop support which is something I tried. But I can find another way to move an existing item into a collection.

Version 1.8.0
Shell 2.0.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64

**Comment by kspearrin** [comment]
Collection management is only available from the web vault at this time.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
