### ISSUE TITLE
Auto-Generate/Autofill not working on Windows 10 

### ISSUE THREAD

**Issue by Jesserey7** [bitwarden/desktop#142]
The App just wont generate a password, well, it will in the extension window, but won't fill the password box. When I right click, the app does appear, but it only knows how to look for saved passwords. I don't want to save all my original passwords only to go through them and generate new ones. That's assuming it would  autofill in that situation,

**Comment by kspearrin** [comment]
The desktop app does not include autofill. You would need the browser extension for that.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by Jesserey7** [comment]
I used the extension for Windows and for chrome, autofill is just not working correctly. IDK, maybe it just works different than what I'm used to. Or I have to make it the default password saving app or something...
