### ISSUE TITLE
sometimes, the asterisk only works in a Full-text Search if escaped

### ISSUE THREAD

**Issue by aDivineDragoness** [bitwarden/desktop#1433]
### Steps To Reproduce

in an Bitwarden account belonging to an organization, while having some passwords inside the org and some just in the personal vault:
- Search: ">-organizationid:\*"

### Expected Result

Only shows Passwords outside the Organization

### Actual Result

no results

### Additional Context

The Problem only occurs ocassionally and restart of the app seems to temporarily fix it.
While occuring, escaping the asterisk (using "a" as mentioned in #1431) makes it work.

### Operating System

Windows

### Operating System Version

21H2

### Installation method

Microsoft Store

### Build Version

1.32.1

**Comment by vphan916** [comment]
Thank you for getting in touch and bringing this to our attention.  Unfortunately, we are unable to reproduce this. We'd like to assist you further. We ask that you please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
