### ISSUE TITLE
Auto-fill extension shortcut not working properly on items with Master password re-prompt (Brave Browser)

### ISSUE THREAD

**Issue by simonsanchezart** [bitwarden/desktop#1457]
### Steps To Reproduce

1. Go to a log-in site where the item in Bitwarden has 'Master password re-prompt' enabled.
2. Press the Auto-fill shortcut (Ctrl+Shift+L)

### Expected Result

A prompt/pop-up to type the master password should appear and then auto-fill the data.

### Actual Result

Nothing happens.

### Operating System

Windows

### Operating System Version

10 Pro

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.32.1

**Comment by Hinton** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by Hinton** [comment]
I believe this is already tracked in https://community.bitwarden.com/t/shortcut-autofill-for-items-with-master-password-reprompt-should-ask-for-the-master-password/39110
