### ISSUE TITLE
Account opens with decryption error 

### ISSUE THREAD

**Issue by filiprd** [bitwarden/desktop#1468]
### Steps To Reproduce

1. Open Bitwarden Desktop
2. Enter correct email and password

### Expected Result

Login, account opens showing all collections and items

### Actual Result

Login, decryption error shown instead of collections and list with no names instead of items

### Screenshots or Videos

<img width="944" alt="bitwarden" src="https://user-images.githubusercontent.com/7045197/161098984-53adf8d2-6dea-453f-8310-ea25a72b7851.png">

### Additional Context

This does not happen always, rather from time to time. 
When it happens, to fix the issue it is usually not enough to just quit the app and try again, but rather to sign out and sign back in again.
I use two accounts on the Desktop client

### Operating System

macOS

### Operating System Version

11.0.1

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.32.1 (2462)

**Comment by aj-bw** [comment]
Hi @filiprd!

Thank you for getting in touch and bringing this to our attention! So far we are unable to reproduce this error you are experiencing.

We'd like to assist you further. We ask that you please contact us using our contact page, here: [https://bitwarden.com/contact](url). You can include a link to this issue in the message content for additional context for our support team. The issue here will be closed and moved over to our Help Desk.
