### ISSUE TITLE
[Windows] App not responding when NOT opening from tray

### ISSUE THREAD

**Issue by Skcyte** [bitwarden/desktop#186]
So basically when trying opening the app from Start menu or Desktop shortcut while the app is already running and in tray the app becomes not responding. And even when I unhide a password then minimize it to tray then opening the app through shortcut/start menu the app hang with password still visible.

**Comment by kspearrin** [comment]
I've not been able to reproduce this issue on Windows 10.

1. I have the application hidden to the system tray.
2. I click on the Bitwarden shortcut on my desktop to re-launch it. It does not open since it is in the system try still.
3. I click the icon on the system tray. Bitwarden opens and is still usable like normal.

**Comment by Skcyte** [comment]
I'm able to open Bitwarden using shortcut after it's minimized to system tray. Is it supposed to not open since the app is already running and minimized to tray? 
[Here's a clip what I do](https://streamable.com/gigxo)

**Comment by kspearrin** [comment]
Thanks for the video. I can reproduce it now.

**Comment by tjyang** [comment]
I confirm this issue also happens to me.
