### ISSUE TITLE
Bitwarden should begin managing the flatpak application.

### ISSUE THREAD

**Issue by kallisti5** [bitwarden/desktop#188]
Per #182, allowing the community to manage the flatpak (or any binary distribution) of bitwarden is a massive security risk and a huge target for malicious actors.

Distro packages offer some level of trust, but letting "the community" manage a binary distribution of an online password management application is horrible security practice and raises some questions about the long-term security of the solution.

Open source only gets you so far.. being able to trust the binary artifacts of an open source project is key.

**Comment by ilya40umov** [comment]
Generally +1 for official Flatpak support, as it will mean timely updates.
Also, there seem to be work from the community to update the package to `1.12.0`:
https://github.com/x80486/com.bitwarden.desktop/tree/release-1.12.0

**Comment by kallisti5** [comment]
Snapd just had a major security vulnerability.. can bitwarden take this on?

https://www.bleepingcomputer.com/news/security/canonical-snapd-vulnerability-gives-root-access-in-linux/

**Comment by kaushalyap** [comment]
@kallisti5  Do not they already have an official version on flathub.org. 8Bit solution is the company behind Bitwarden

**Comment by cscharf** [comment]
BTW, this is on our DevOps Roadmap for the upcoming year.

**Comment by ndrewtl** [comment]
@cscharf Hope you're doing well-- Can you tell us if is this still on your TODO for 2021?

**Comment by baarkerlounger** [comment]
@cscharf is this still in the backlog and if so worth keeping this open?

**Comment by cscharf** [comment]
Hi @baarkerlounger , thank you for the response! This is still on our backlog, however since this would be a change/enhancement to our current product support I'm going to close this item and refer everyone over to our community forums' [post](https://community.bitwarden.com/t/bitwarden-should-manage-its-flathub-application/30823) on the same where you and others can vote on it, and where our technical evangelist and product team can keep a closer eye on it.
