### ISSUE TITLE
Release verification

### ISSUE THREAD

**Issue by ffflorian** [bitwarden/desktop#201]
Hi,
currently it's impossible to verify the released desktop apps. The commits to the master branch are also not signed.

Ideally, you would create a file with SHA256 hashsums for all released files, sign this hashsum file with a known PGP key and release it along with the other files.

See [syncthing's releases](https://github.com/syncthing/syncthing/releases) for a good example.

**Comment by ffflorian** [comment]
Sorry, I realized only now that there is a YAML file which includes a SHA512 hash. Still, the hashsum file is not signed.

**Comment by ffflorian** [comment]
@kspearrin any update on this?

**Comment by m4teh** [comment]
This is troubling. The issue has unresponded to since January 2019, which is even worse.
It still appears impossible to verify hashes on released files. The git releases section includes .yml files with hashes but these do not match the sha512sum on downloaded binaries. What's going on?

latest-linux.yml

> version: 1.16.6
>
>files:
  >- url: Bitwarden-1.16.6-x86_64.AppImage
   > sha512: >EawRh8xzFYbwfJxh178EOyXkoMdjpb3nDc+XkaUh3XRisTitsi8rGbd1+HsP5/WvZnqqp4cUFAqAypW1LhR77Q==
    size: 68644225
    blockMapSize: 73109
>path: Bitwarden-1.16.6-x86_64.AppImage
sha512: EawRh8xzFYbwfJxh178EOyXkoMdjpb3nDc+XkaUh3XRisTitsi8rGbd1+HsP5/WvZnqqp4cUFAqAypW1LhR77Q==
releaseDate: '2019-09-30T15:23:28.092Z'

[user@Personal Downloads]$ sha512sum Bitwarden-1.16.6-x86_64.AppImage
11ac1187cc731586f07c9c61d7bf043b25e4a0c763a5bde70dcf9791a521dd7462b138adb22f2b19b775f87b0fe7f5af667aaaa78714140a80ca95b52e147bed  Bitwarden-1.16.6-x86_64.AppImage

**Comment by kspearrin** [comment]
@m4teh The hashes match. The one in the release file is base64. Your command is outputting hexadecimal.

**Comment by m4teh** [comment]
I see that it does indeed match. Thanks for clarifying that.
