### ISSUE TITLE
Vulnerability to memory attacks?

### ISSUE THREAD

**Issue by pdarcos** [bitwarden/desktop#217]
Hi,

I opened this ticket in the browser repo but it is probably more related to the web vault, so here it is again.
Have you read https://www.forbes.com/sites/kateoflahertyuk/2019/02/20/password-managers-have-a-security-flaw-heres-how-to-avoid-it/ yet?

It doesn't mention bitwarden in the article but I was wondering how vulnerable bitwarden client side apps are to these memory attacks (desktop, mobile and browser).

Cheers

**Comment by kspearrin** [comment]
Bitwarden clears any sensitive cached vault data, as well as encryption keys from memory whenever the application enters a locked state. We also reload the application's renderer process after 10 seconds of inactivity on the lock screen to make sure any managed memory addresses which have not yet been garbage collected are also purged.

**Comment by edermi** [comment]
There seem to be tools that allow (amongst other interesting attacks) to parse memory from Bitwarden:
https://github.com/checkymander/VaultBreaker/

I guess it may be difficult to ensure that the key is wiped from memory because the Bitwarden apps are Electron based and the runtime may decide to perform optimizations any optimizations to "useless" operations like nulling an array.

**Comment by pdarcos** [comment]
Thanks for the feedback guys!
