### ISSUE TITLE
[Linux] Incorrectly displayed icon in system tray

### ISSUE THREAD

**Issue by AlexMak58** [bitwarden/desktop#251]
Incorrectly displayed icon in system tray.
![Screenshot_20190506_005317](https://user-images.githubusercontent.com/34411074/57200925-10831080-6f81-11e9-8368-7a0f30e4f11f.png)

**App**:
![Screenshot_20190506_005708](https://user-images.githubusercontent.com/34411074/57200904-cdc13880-6f80-11e9-8cde-ad425bc90469.png)

**OS**:
![Screenshot_20190506_005815](https://user-images.githubusercontent.com/34411074/57200923-0d882000-6f81-11e9-827c-ef0bd7aeb7f7.png)

**Comment by RogueScholar** [comment]
@AlexMak58 Yeah, you're not alone on this one, but thankfully there's a fix in the form of a tool called [Hardcode-Tray](https://github.com/bilelmoussaoui/Hardcode-Tray) provided you have a compatible icon theme installed, of which [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) is decided the most complete. When applications hardcode the path to their icons instead of following the Freedesktop XDG specs, not only are they un-themeable but often your desktop environment can't scale them properly; it's the scaling issue that's bitten you on the backside here. Mostly you see this from the apps built using Electron as it packages the image files within the binary itself, but there are plenty of non-Electron offenders too. You should read up on it when you have the time, but I can help get you started right here. :rescue_worker_helmet:

Bear in mind that my facility with Arch and its derivatives is somewhat thin; I ran Manjaro on my daily driver laptop for close to a year, but that was over two years ago and I haven't yet found a need to go back to it. The needed packages are all from the AUR as well, so this'll require one of the assorted pacman wrappers to accomplish painlessly. Since I'm told the ones I used back then (pacaur & yaourt) are no longer copasetic I'm going to show the commands for doing this with [yay](https://github.com/Jguer/yay), but of course any of them will most likely get you to the same result so use your best judgment/favorite one. Oh, and the (_cough_, taillight, _cough_) warranty on these instructions lasts only as long as my browser tab is open, so _**caveat utilitor**_ and all that jazz. :smile: 

```bash
# Here come the goodies
yay -S --needed hardcode-tray-git sni-qt-patched-git lib32-sni-qt-patched-git papirus-icon-theme-git
# Ma! Start the car!
sudo -E hardcode-tray --conversion-tool RSVGConvert --dark-theme Papirus-Dark --light-theme Papirus -o bitwarden.electron -a
```

There you have it; you should be ready to rock and roll. You'll also need to restart, naturally, to see the new icon in the panel. If it works and you like what you see, you can run that last command again without the `-o bitwarden.electron` flag and it'll find any other similarly naughty apps you have installed and give them the same treatment. Getting all the other well-behaved apps' panel icons to match is a simple matter of traipsing over to System Settings -> Appearance -> Icons and selecting one of the newly-available Papirus themes then clicking Apply.

Best of luck to you, and much respect from a fellow KDE Plasma devotee. :vulcan_salute:
