### ISSUE TITLE
Support TouchID on Mac

### ISSUE THREAD

**Issue by nicad** [bitwarden/desktop#261]
It would be great to be able to unlock BitWarden using TouchID on Mac. Ideally with a config to choose how often to re-prompt for the master passwords (X minutes/Days/until reboot).

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by henrik242** [comment]
Electron v6 [has support for TouchID](https://github.com/electron/electron/pull/16707) and BitWarden [has now been upgraded to electron 6](https://github.com/bitwarden/desktop/commit/c344c5c13d38f242c049f1d04fd5e89a0cf2f769), so we're getting closer to fixing this [feature request](https://community.bitwarden.com/t/touch-id-support-for-macos/568).

**Comment by Evertt** [comment]
@henrik242 though in that thread, on January 19th [Billy_Lo says](https://community.bitwarden.com/t/touch-id-support-for-macos/568/86):

> 2. Browser client / Chrome Extension: Chrome does support WebAuthn with Mac Touch ID (Safari doesn’t yet). I will need to add a WebAuthn server to handle registration of the TouchID as system authenticator and add a button to the web app to call WebAuthn API to authenticate. It’s doable, but I won’t have sufficient cycles to do all the work; and it will be limited to be usable on Chrome/Mac.

That sounds to me like it doesn't add enough value for him to spend his limited time on it. What do you think about that? Do you think other people will jump in?

**Comment by jab** [comment]
> We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a section for submitting, voting for, and discussing product feature requests like this one.
>
> Please sign up on our forums and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.
>
> This issue will now be closed. Thanks!

Since no one else here has linked to it yet, here is the corresponding feature request thread on the community forums: https://community.bitwarden.com/t/touch-id-support-for-macos/568

From a quick look at the thread, it looks like there's interest in this feature both from users and from maintainers. Given that, would you be willing to reopen this issue, using it just for tracking progress on development (so any other discussion should still go in the community forum)? This allows users who only want to find out when this feature is released to subscribe to this issue, rather than subscribing to the forum thread, which is a lot more noisy. I'm a paying user and I am in this category, for whatever it's worth.

Thanks for your consideration and for the work on Bitwarden, it's fantastic.
