### ISSUE TITLE
Loss of data when creating a new entry without hitting save

### ISSUE THREAD

**Issue by Bios-Marcel** [bitwarden/desktop#267]
When creating a new entry in the vault, you can enter everything and hit save. However, if you forget to hit save and close the app or select a different item, your stuff gets thrown away.

It would be really nice if you had at least a prompt like "Hey, do you want to save this?".
I have now lost access to a couple of accounts of the years because of this.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
