### ISSUE TITLE
Bitwarden hanging at loading screen

### ISSUE THREAD

**Issue by psivesely** [bitwarden/desktop#271]
Bitwarden hangs at loading screen.

![Screenshot from 2019-07-07 13-45-58](https://user-images.githubusercontent.com/3538418/60768593-9aed0b00-a0bd-11e9-871a-b4d2b5872137.png)

If I try to launch via the command-line it fails without an error message.

Running on Debian 10. Installed via `snap`.
```
Version 1.14.0
Shell 3.0.14
Renderer 66.0.3359.181
Node 10.2.0
Architecture x64
```

**Comment by nvesely** [comment]
So the desktop client is working again, but the weird thing is I was able to use the online vault during the time it wasn't. Without knowing anything about your server infrastructure, I'd guess there was a partial outage, and the client is simply not programmed right to be able to route around such outages. I'll leave this open because ideally there should be enough redundancy (and client code that knows how utilize it) in your infrastructure such that clients do not experience service interruptions.

**Comment by kspearrin** [comment]
We did not have a service disruption today, so I am not sure what the problem was. The desktop app is supposed to work offline regardless.

**Comment by JoelCourtney** [comment]
I have the same issue, on Ubuntu 18.04.3. BitWarden 1.15.2. I have tried running the AppImage directly, and using snap. I've also tried running the Windows version in wine, but of course that didn't work because wine.

It got past the loading screen once. This was the first time I tried after changing my password. Since then it has gone back to hanging on the loading screen. Here is the stack trace from console:

Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new Conf (vendor.js:120870)
    at new ElectronStore (vendor.js:120829)
    at new electronStorage_service_ElectronStorageService (electronStorage.service.ts:21)
    at Module.585 (services.module.ts:91)
    at __webpack_require__ (bootstrap:78)
    at checkDeferredModules (bootstrap:45)
    at bootstrap:151
    at bootstrap:151

**Comment by JoelCourtney** [comment]
Fixed by cloning either bitwarden/jslib or bitwarden/desktop and running the bitwarden command inside one of those directories.

**Comment by JoelCourtney** [comment]
It looks like it depends on one or all of the following json files:
package.json
package-lock.json
tsconfig.json
tslint.json

Because running bitwarden from any directory that doesn't have those files results in the above error.

**Comment by AlexKalopsia** [comment]
Experiencing a similar problem. Hosting BitWarden on my Synology NAS within a Docker container. If I go on my BW page I keep seeing the loading icon no matter what.
