### ISSUE TITLE
backdoor framework electron

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [bitwarden/desktop#295]
https://youtu.be/qDTKYNGsyuI

https://arstechnica.com/information-technology/2019/08/skype-slack-other-electron-based-apps-can-be-easily-backdoored/

Tsakalidis demonstrated a tool he created called BEEMKA, a Python-based tool that allows someone to unpack Electron ASAR archive files and inject new code into Electron's JavaScript libraries and built-in Chrome browser extensions. The vulnerability is not part of the applications themselves but of the underlying Electron framework—and that vulnerability allows malicious activities to be hidden within processes that appear to be benign. Tsakalidis said that he had contacted Electron about the vulnerability but that he had gotten no response—and the vulnerability remains.

**Comment by kspearrin** [comment]
This vulnerability is not new. It's been known since January 2019. https://www.contextis.com/en/blog/basic-electron-framework-exploitation

There isn't really anything we can do about it since it is an upstream issue. This vulnerability also requires that the host already be compromised. If the host is compromised it would be hard to expect any application to still be safe.

**Comment by kspearrin** [comment]
Closing since this is an upstream issue in Electron.

**Comment by SDRPatriot** [comment]
Shouldn't Electron be addressing the issue instead of hiding or avoiding it?  I understand that the host would have to be compromised already, but with all the plugins in browsers people use now it's not hard to imagine some issues.  Is this vulnerability detected by any known A/V or Malware software even?
