### ISSUE TITLE
Why I can't delete the subfolder when I delete a folder?

### ISSUE THREAD

**Issue by hewittchoi** [bitwarden/desktop#347]
I import the data from keepass, and I created lots of folder before. When I deleted a folder, all the subfolders appear, what? I have to delete them one by one?

**Comment by kspearrin** [comment]
Yes, folders must be deleted individually. If you want to start over, you can purge the entire vault under Settings and import all of your data again.

**Comment by dangelion** [comment]
@kspearrin It would be very useful if deleting a parent folder it deletes all the sub folder and passwords

**Comment by cscharf** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
