### ISSUE TITLE
Exclude from Dock and ⌘-Tab Application Switcher.

### ISSUE THREAD

**Issue by martinorob** [bitwarden/desktop#365]
Please make the desktop app for Mac to be excluded from Dock and ⌘-Tab Application Switcher so I can use it only from try bar (like other desktop app like bitwarden)

Thanks

**Comment by tehguitarist** [comment]
Will second the ability to have bitwarden in the menu (top bar) on MacOS, and not have it in the dock (or the option between, one, the other, or both).

If the code is needed, these opensource apps do it:

https://github.com/oldj/SwitchHosts
https://github.com/AdguardTeam/AdguardForMac

**Comment by overheadhunter** [comment]
Make it optional, though. I like to be able to ⌘-tab. 😉

**Comment by cscharf** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
