### ISSUE TITLE
Password History is shown in plain text

### ISSUE THREAD

**Issue by wfernandes** [bitwarden/desktop#466]
## Describe the Bug

When displaying password history, the password is shown in plain text. It should be treated as a password field. It should be hidden by default with the eye logo to show it.

## Steps To Reproduce

1. Go to Desktop client
2. Create a login entry with password. Save.
3. Edit the same entry and update the password.
4. Click on Password History.

## Expected Result
Password History to be hidden

## Actual Result

Password History appears in clear text.

## Screenshots or Videos

<img width="496" alt="Screen Shot 2020-06-18 at 8 23 16 PM" src="https://user-images.githubusercontent.com/2303039/85090355-2746ef80-b1a2-11ea-9aa0-8b6d1190ff36.png">

## Environment

- Operating system: Mac OS Catalina 10.15.4 
- Build Version Version 1.18.0 (1.18.0)

**Comment by tgreer-bw** [comment]
Hi @wfernandes  - thanks for the feedback! We use GitHub issues specifically for bug reports. This is actually intended function since there are a number of steps to display the password history, it's fairly obfuscated by default.  

If you'd like to see some additional UI/function for password history, please open a topic here: https://community.bitwarden.com

**Comment by wfernandes** [comment]
Makes sense. Thanks for the prompt response.
