### ISSUE TITLE
Erase Master Password in memory after login

### ISSUE THREAD

**Issue by winkler-winsen** [bitwarden/desktop#476]
There is an article in German IT-magazine [c't 15/2020](https://www.heise.de/select/ct/2020/15/2015514091680573293) page 28. "Passwortmanager: Sicherheitstest |  Dichtheitsprüfung | Passwortmanagern auf Speicher und Netzwerkverkehr geschaut" (translated: Password managers: security test | leak test | password managers on memory and network traffic protected" (behind pay wall)

The authors test common password managers if they keep (master) password in memory before and after login and after logout. It seems they test only the windows versions.

For Bitwarden, they found **multiple copies of master passwords in memory dumps** after login. Before login and after logout, they didn't find master password no more in memory.

> ![grafik](https://user-images.githubusercontent.com/43114182/86779970-7aeb8100-c05c-11ea-9ac0-71ce701a0629.png)

>  Dieser Wunsch blieb unerfüllt: Lediglich vor der Eingabe des Masterpassworts konnten wir bei keinem Produkt die Existenz dieses Generalschlüssels im Speicher nachweisen. Sobald aber das Masterpasswort eingegeben war, konnte man es bei fast allen Programmen im Klartext im Speicher vorfinden. Manche vervielfältigten es sogar im Speicher. Es taucht an bis zu 20 verschiedenen Adressen auf. Dass das auch anders geht, zeigen Keepass und Sticky Password. Bei denen gelang es uns nicht, das Masterpasswort im Speicher zu finden.

> Nur einem Teil der Programme gelang es, beim Verriegeln auch das Masterpasswort wieder aus dem Speicher zu entfernen: 1Password, Bitwarden, Keepass, Keeper und Sticky Password. Bei den anderen blieb es weiter zugänglich. Trauriger Rekordhalter war Blur: Es verdoppelte die Anzahl der Fundstellen des Masterpassworts von der Anmeldung mit rund 20 auf fast 40 nach der Abmeldung. Ebenso vervielfachten sich bei Avira die Fundstellen auf immerhin zwölf. 

[DeepL Translation](https://www.deepl.com/translator#de/en/%20Dieser%20Wunsch%20blieb%20unerf%C3%BCllt%3A%20Lediglich%20vor%20der%20Eingabe%20des%20Masterpassworts%20konnten%20wir%20bei%20keinem%20Produkt%20die%20Existenz%20dieses%20Generalschl%C3%BCssels%20im%20Speicher%20nachweisen.%20Sobald%20aber%20das%20Masterpasswort%20eingegeben%20war%2C%20konnte%20man%20es%20bei%20fast%20allen%20Programmen%20im%20Klartext%20im%20Speicher%20vorfinden.%20Manche%20vervielf%C3%A4ltigten%20es%20sogar%20im%20Speicher.%20Es%20taucht%20an%20bis%20zu%2020%20verschiedenen%20Adressen%20auf.%20Dass%20das%20auch%20anders%20geht%2C%20zeigen%20Keepass%20und%20Sticky%20Password.%20Bei%20denen%20gelang%20es%20uns%20nicht%2C%20das%20Masterpasswort%20im%20Speicher%20zu%20finden.%0A%0ANur%20einem%20Teil%20der%20Programme%20gelang%20es%2C%20beim%20Verriegeln%20auch%20das%20Masterpasswort%20wieder%20aus%20dem%20Speicher%20zu%20entfernen%3A%201Password%2C%20Bitwarden%2C%20Keepass%2C%20Keeper%20und%20Sticky%20Password.%20Bei%20den%20anderen%20blieb%20es%20weiter%20zug%C3%A4nglich.%20Trauriger%20Rekordhalter%20war%20Blur%3A%20Es%20verdoppelte%20die%20Anzahl%20der%20Fundstellen%20des%20Masterpassworts%20von%20der%20Anmeldung%20mit%20rund%2020%20auf%20fast%2040%20nach%20der%20Abmeldung.%20Ebenso%20vervielfachten%20sich%20bei%20Avira%20die%20Fundstellen%20auf%20immerhin%20zw%C3%B6lf.)

ToDo:
- Please check if it is possible to erase master password after login (windows versions)
- Please check the same issue on desktop for other platforms (OS X/macOS, Linux)
- Please check browser extentions, if they leak master password

If you need a translated version, I can try to translate article for you. Pls message me.

**Comment by kspearrin** [comment]
Hi. Bitwarden uses Electron for our desktop application which does not allow for us to manage address spaces of the UI (renderer) thread where your master password is entered. This is similar to how a webpage works. As I believe your article points out (I do not speak German), we do clean up memory promptly whenever a user logs out or locks the application. We do this by reloading the renderer process (similar to refreshing a webpage).

**Comment by BeNeDeLuX** [comment]
Ok, that was easy!
1.) Just export the current memory from the Bitwaren process in a dump file: 
![RAM_Export](https://user-images.githubusercontent.com/1895086/86959650-80c98b00-c15e-11ea-8f6b-b3c7cdabc207.PNG)

2.) Check the dump file with a hex editor of your choice and search for your clear text master password -> **et voilà**
![HxD-screenshot](https://user-images.githubusercontent.com/1895086/86959652-81fab800-c15e-11ea-8b62-d23dc86b29fd.PNG)

- You don´t need any Administrator permissions for that attack
- A malware could do the same and extract all the readable text out of memory for the bitwarden process. Since bitwarden is an online service, the attacker can directly try out the discovered clear text passages as password
- I´m sure most of the users keep bitwaren open (unlocked) so there is a wide attack vector
- 2FA could help but does not solve the main problem

I have to say that i don´t feel that secure anymore with that conclusion

**Comment by cscharf** [comment]
Taking notes and linking this thread from nodejs: https://github.com/nodejs/node/issues/30956.
Perhaps certain values should be stored in the user's keystore directly vs. in memory in electron; although once a string is allocated not sure you can prevent that. Just thinking out loud on this one.

**Comment by sklages** [comment]
c't tested Windows and Android. Would be interesting how this issue behaves on Linux (Linux and Android are my workhorses).

**Comment by phloose** [comment]
Maybe i am naive but wouldn't it make sense to directly hash the masterpassword after typing it into the form? That way it would not be stored as plain text in memory from the beginning.

**Comment by phloose** [comment]
Although it would require to redesign certain parts of the current implementation but this post on stack overflow describes the exact same situation and proposes to use a Buffer object:

https://stackoverflow.com/questions/53887729/how-do-i-clean-up-sensitive-node-js-buffers-from-electron-renderer-process-memor

The used buffer object is filled with zeros after the login is done. When you only pass this single object reference it should be possible to keep easily keep track of it and overwrite it in the end. 

By using the Buffer object i was able to reduce the amount of clear text passwords in the memory dump from 5 to 2 when the initial login is used and from 3 to 1 when the lock page is used... After all a slight improvement :)

I am by no means a security nor a JS/TS expert. I am just interested in finding a solution because i like bitwarden very much and want to help make it better!

**Comment by phloose** [comment]
Btw i just saw, that you @kspearrin asked a question concering this issue ~2 years ago on stackoverflow:

https://stackoverflow.com/questions/53887729/how-do-i-clean-up-sensitive-node-js-buffers-from-electron-renderer-process-memor

Why not go that way? Seems to be a better way to have an object that you can keep reference to and clear it if wanted

**Comment by kspearrin** [comment]
> Btw i just saw, that you @kspearrin asked a question concering this issue ~2 years ago on stackoverflow:
> 
> https://stackoverflow.com/questions/53887729/how-do-i-clean-up-sensitive-node-js-buffers-from-electron-renderer-process-memor
> 
> Why not go that way? Seems to be a better way to have an object that you can keep reference to and clear it if wanted

Because it didn’t solve the problem. The problem appears to be the input password html element on the page. Not a variable that once held a password.

**Comment by phloose** [comment]
Ah i see, was thinking the same... And there is no method to clear floating references to input element values?

**Comment by kspearrin** [comment]
Not that I have found

**Comment by phloose** [comment]
Just an idea: What about to redirect to another freshly loaded page after successful authentication showing the unlocked vault? Maybe some kind of session cookie holding a token could be used (I am not an expert in this, just thinking out load). That way the references to the old form fields _could_ be garbage collected...

**Comment by xrayn** [comment]
I have 2 questions. Is this still an issue and does this also affect the browser extension. The latter has not been answered yet, in this thread.
