### ISSUE TITLE
Loading animation not displaying properly

### ISSUE THREAD

**Issue by vachan-maker** [bitwarden/desktop#479]
## Describe the Bug
The loading animation(spinning dots) sometimes does not load properly. A spinning rectangle appears and inside there are two characters F, O. 

## Steps To Reproduce
Open the Bitwarden **application**  or launch the Bitwarden **extension**
OCCURS ONLY SOMETIMES

## Expected Result
The animation should be smooth and the rectangle should not appear

## Actual Result

A rectangle appears for a few seconds

## Environment

Windows 10

Version 1.19.0
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

**Comment by SDRPatriot** [comment]
I have noticed something similar.  It seems to be locking up the browsers.
I have it on Firefox, Opera and Brave along with the desktop install.  in
the evening it appears to get worse.  When I try to open the extension
it'll just sit there at the loading screen and never load properly.  When
it happens it happens on all extensions and desktop versions.  Usually ends
in a full system reboot.

I didn't report it because I'm not certain it's Bitwarden or something
affecting Bitwarden.  Maybe a security mechanism of sorts.  Since someone
mentioned it I figured I'd add my experience to it.   Again not 100% sure
it's Bit Warden because it seems to happen late night so it could be
MalwareBytes or Webroot causing an issue.  The other possibility is
Microsoft Onedrive updater.  All of those programs are potential problems.
Let me know if you are aware of any compatibility issues.

Windows Info

Win 10 Pro x64
Version 2004
Build: 19041.329

BitWarden Info
Bit Warden Extension Version: 1.44.3 Opera
Bit WArden Extension Version: 1.45.0 FireFox
Bit WArden Extension Version: 1.45.0 Brave

Desktop App
Version 1.19.0
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64



SDRPatriot
