### ISSUE TITLE
Windows installer won't work in restricted environment

### ISSUE THREAD

**Issue by mirostauder** [bitwarden/desktop#508]
## Describe the Bug

most office/workplace environments have restricted internet access
Windows installers won't work in restricted environments
i.e. when downloads are blocked/restricted

## Steps To Reproduce

block file downloads or disconnect network
run Bitwarden-Installer-1.20.1.exe /S

## Expected Result

Bitwarden installs or updates installed version

## Actual Result

popup 'Please check you internet connection and retry.'
(also typo - you -> your)

## Screenshots or Videos

![Screenshot at 2020-08-05 12-33-32](https://user-images.githubusercontent.com/29940727/89403351-70cea800-d718-11ea-939f-43ab360a0482.png)

## Environment

windows

## Additional Context

I know I can download the 7z file manually, that's not a solution for most deployment tools
a proper one file offline installer is needed

**Comment by kspearrin** [comment]
I am not sure I understand the solution. How can we provide an updated version if the application cannot access the internet?

**Comment by mirostauder** [comment]
I am talking about a "Full Installer" aka "Standalone Installer" aka "Offline Installer"
In managed environments, an "Offline Installer" is once downloaded, verified, and then centrally deployed.
The installer should not access the internet.
The end application accessing internet is something different.
Also most update management tools deploying updates or new installs, require a **single file** "Offline Installer".

**Comment by cscharf** [comment]
@kspearrin, Could this be accomplished using the `electron-builder` windows target of `nsis` as an option? Today we're using `nsis-web` but not the full `nsis` packaging option for distribution (assuming because this file gets pretty large). The `nsis-web` package is smaller and relies on downloading the core package file based on machine architecture from the internet (hence the need for connectivity) whereas the full `nsis` target includes all of the possible architecture packages inside of it (which makes it pretty big, but "offline").

**Comment by kspearrin** [comment]
@cscharf The problem is that electron-builder doesn't support producing both nsis and nsis-web at the same time. See https://github.com/electron-userland/electron-builder/issues/2588

@mirostauder Could just distribute the web installer with the downloaded .7z assets bundled with it in the same directory? That way avoids having to download anything.

**Comment by netroby** [comment]
+1, need the standalone installer , with no requirement for network install file download

**Comment by cscharf** [comment]
Have put a todo on our DevOps backlog to try to figure out a way to package a standalone, offline installer. Not sure about timing at this point however.
