### ISSUE TITLE
Keyboard shortcut for OTP (Feature request)

### ISSUE THREAD

**Issue by SwissTico** [bitwarden/desktop#511]
Hello!

It's not a bug, only a feature request...

Bitwarden Desktop included keyboard shortcuts to copy username and password that are very practical for all logins that don't belong to a browser.

As a OTP user, it would be very practical to have a keyboard shortcut as well for the OTP field. Could it be implemented in a future release?

Thanks a lot :-)

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
