### ISSUE TITLE
AppImage updates fail to install

### ISSUE THREAD

**Issue by PHLAK** [bitwarden/desktop#541]
## Describe the Bug

Updates fail to install with an error. I've installed Bitwarden via the AppImage.

## Steps To Reproduce

1. Go to Help → Check for Updates
2. Click on "Yes" when prompted with "An update was found. Do you want to download it now?"
3. Click on "Restart" when prompted with "... Do you want to restart and update now?"

## Expected Result

Bitwarden should update to the new version and restart.

## Actual Result

An error window pops up (see screenshot below).

## Screenshots or Videos

![Screenshot 2020-09-16 10:25:53](https://user-images.githubusercontent.com/53531/93371587-73d4b200-f807-11ea-9dd9-056b26793b75.png)

## Environment

- Operating system: Ubuntu 20.04.1
- Build Version (go to "Settings" → "About"): 1.21.0

![image](https://user-images.githubusercontent.com/53531/93372351-a337ee80-f808-11ea-8800-56153ef1a803.png)

**Comment by Gambloide** [comment]
Based on your logs it looks like you are using AppImageLauncher.
It looks like a problem rooted in electron-builder is influencing the update function of AppImageLauncher:
https://github.com/electron-userland/electron-builder/issues/4046

Apart form the workaround documented in the linked issue, the only real "solution" seems to be to not use AppImageLauncher until this issue is resolved.

Note: I have not used AppImageLauncher nor am I able to share any experiences with the workarounds described. I just stumbled across your report while researching a similar problem.

**Comment by TheAssassin** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/4046#issuecomment-699743169.

**Comment by MGibson1** [comment]
It looks like the upstream fix solved this issue, so I'm going to close it. Thanks @Gambloide and @TheAssassin for linking that solution and making this easy!
