### ISSUE TITLE
Enable integration with browser plugins

### ISSUE THREAD

**Issue by JayDoubleu** [bitwarden/desktop#559]
I am using 3 browsers with multiple profiles in each. Currently I have to install the browser extension in each browser/profile and log in to all of them separately.

It would be nice to see desktop app behaving like Dashlane, meaning I install desktop app, log into it once and then I can instruct browser extensions to use the desktop app as a source.

**Comment by Greenderella** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests/5) like this one.

Please sign up on our forums and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

**Comment by JayDoubleu** [comment]
Or, I can go back to dashlane. :)

**Comment by mhunter8** [comment]
> Or, I can go back to dashlane. :)

It's a good idea.  I would vote for it.  If you aren't going to enter it, I will.  Please advise.

**Comment by mhunter8** [comment]
One other comment, I believe this has already been requested here:  https://community.bitwarden.com/t/login-to-browser-extensions-when-logging-into-desktop-app-and-vice-versa/1635

@JayDoubleu please verify...
