### ISSUE TITLE
Is there any plan to enhance the notes capabilities ?

### ISSUE THREAD

**Issue by rajmondburgaj** [bitwarden/desktop#582]
I am planning to use bitwarden as my main notes tool but seems not yet there because the notes textbox is very simple and does not offer much. Is there any plan to add markdown or 'rich text editor' capabilities to it ?

Also would be nicer if the content area is resizable according to the screen size, because in wide screens the content look so small and very uncomfortable to read!

The same questions apply for web as well(_except resizable thingy which is possible to do in web_)

As an example check below how much real estate is wasted. In this case there is not much text but i just wanted to showcase it.

![image](https://user-images.githubusercontent.com/7545874/98440764-e2910600-20fa-11eb-86c7-a00e1316e0c3.png)

**Comment by Greenderella** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests/5) like this one.

Please sign up on our forums and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.
