### ISSUE TITLE
Improve font rendering by setting Electron background

### ISSUE THREAD

**Issue by Lombra** [bitwarden/desktop#608]
Electron has a bug (feature?) where if you don't set the window background to white, all text will use grayscale antialiasing. Set the background color to #fff in order to enable subpixel antialiasing, which makes text look much better.

For Bitwarden, you need to do it here:
https://github.com/bitwarden/jslib/blob/63fe38b3f4dddd701b1a8da8a89e70c9d7fbc706/src/electron/window.main.ts#L106

https://www.electronjs.org/docs/faq#the-font-looks-blurry-what-is-this-and-what-can-i-do

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
