### ISSUE TITLE
CSV export does not include cards?

### ISSUE THREAD

**Issue by jtv** [bitwarden/desktop#610]
## How to reproduce

1. Add a "Card" entry to your vault.
2. Export the vault to CSV.

## Expected Result

I would expect the exported CSV output to include the card.

## Actual Result

The card is simply missing from the output.  It _is_ included when I export to JSON.

## Environment

- Operating system: Ubuntu 20.04.
- Build Version: 1.23.1.

## Additional Context

This is my first attempt to use Bitwarden. However the problem also happens if I first add a login entry and then create a new card entry.

I'm assisting in a prospective migration to Bitwarden.  I was trying the export in order to reverse-engineer the CSV format, and figure out how to migrate existing data off the existing product.  The CSV examples do not include a Card entry.

**Comment by clayadams5226** [comment]
This is currently expected behavior. Users should use JSON whenever possible. That said, we have updated our help articles to make this more clear to the user. 

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
