### ISSUE TITLE
Desktop app on Linux is not accessible for blind users

### ISSUE THREAD

**Issue by alex19EP** [bitwarden/desktop#621]
## Describe the Bug

i am a blind windows and linux user. for the best accessibility experience on linux the app need to be updated to at least electron 10 (11 would be better). 

## Steps To Reproduce

try to use app with orca on linux.

## Expected Result

app would be read by screen reader. 

## Actual Result

app isn't accessible because cromium version is too low.

## Environment

- Operating system: any linux
- Build Version 1.23.1

**Comment by cscharf** [comment]
Thank you for the report @alex19EP , we'll be focusing on Accessibility and some of these topics in the first quarter of this coming year. I'll add this to the list of items to explore.

What assistive tech are you using in Windows? JAWS, NVIDA, etc.? Is that working for you in Windows at the moment and the problem is just with Orca on Linux?

**Comment by alex19EP** [comment]
> 
> 
> Thank you for the report @alex19EP , we'll be focusing on Accessibility and some of these topics in the first quarter of this coming year. I'll add this to the list of items to explore.
> 

glad to hear that.

> What assistive tech are you using in Windows? JAWS, NVIDA, etc.? Is that working for you in Windows at the moment and the problem is just with Orca on Linux?

on windos desktop app is accessible. i am using NVDA on windows.

**Comment by Mart124** [comment]
Electron 11 also [supports Apple M1](https://www.electronjs.org/blog/electron-11-0), which would really be great to have 👍

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by alex19EP** [comment]
> 
> 
> We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.
> 
> Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.
> 
> This issue will now be closed. Thanks!

i think this issue contains bug. and it's development related. so it's need to be reopened.

**Comment by djsmith85** [comment]
Hi @alex19EP electron has been bumped to version 11. Hopefully you'll have a better experience with the next release.

**Comment by alex19EP** [comment]
> 
> 
> Hi @alex19EP electron has been bumped to version 11. Hopefully you'll have a better experience with the next release.

yes. I have compiled the current master. everything works great. 
thank you.
