### ISSUE TITLE
Cannot save after editing a login

### ISSUE THREAD

**Issue by SudaFrancais** [bitwarden/desktop#622]
## Steps To Reproduce

1. Go to Bitwarden client in Windows 10
2. Click on any login record and then click on 'edit'
3. Add comments to Notes field
4. Click on 'Save'

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/76430504/102766845-0a70bc00-437f-11eb-9116-5447421f11c6.png)

![image](https://user-images.githubusercontent.com/76430504/102767288-9a166a80-437f-11eb-9160-75f761a06fb1.png)

## Environment

- Operating system: Windows 10
- Build Version (go to "Settings" → "About"): 1.23.1

## Additional Context

 This is on my work PC, I cannot rule out my compan's IT systems/firewalls as the cause. I do not see this issue in the client running on my home Linux PC.

**Comment by SergeantConfused** [comment]
Hi there,

I'm unable to reproduce this. This can be caused by an application that's interfering with the traffic to your vault. I recommend you consider uninstalling, rebooting, and reinstalling the desktop client. You can also check if the portable version works better in your environment (https://github.com/bitwarden/desktop/releases/tag/v1.23.1).
Lastly, you can ask your IT department if they have anything to share on this.

I hope you find this helpful. Please let me know if you have any further questions.


All the best,

**Comment by SudaFrancais** [comment]
Hello,

I appreciate your fast reply, thank you for your support.

Regards
