### ISSUE TITLE
Data loss after vault timeout

### ISSUE THREAD

**Issue by firetechnology** [bitwarden/desktop#627]
## Describe the Bug

Lost data (both new entries and changes) in case of making a break that is longer than the vault timeout.
Some registration processes take more than a minute to complete but the vault timeout discards any changes without a warning or possibility to restore them.

## Steps To Reproduce

1. Set your vault timeout in settings to the minimum value of one minute (makes reproducing faster)
2. Create a new entry (or edit an existing one)
3. Do not click on save, but wait a minute or focus another window for a minute
4. Turn back to Bitwarden and enter your password/pin

## Expected Result

Bitwaren opens the editor again containing the unsaved changes.

## Actual Result

Bitwarden opens the list view and has obviously discarded the unsaved changes.

## Environment

- Operating system: Windows 10, macOS Big Sur
- Build Version (go to "Settings" → "About"): 1.23.0

## Additional Context

This problem can lead to account lockout and loss of very important documents.

**Comment by Tyri0n** [comment]
This! Just had this happen again and it really shouldn't.

**Comment by cscharf** [comment]
Hi @firetechnology , thank you for sharing this. This particular request is a non-trivial change in behavior to be constantly saving in-progress "state" in a secure/encrypted manner and re-loading that state after an unlock. Understand that the way Bitwarden works when the vault locks is to abandon all in-state memory (decrypted), forcing the user to enter their master password to access the key and unlock the vault again (decrypt that data). This doesn't lend itself well to maintaining/preserving the "page", form or state across lock boundaries without significant code/handling to do just that.

Give that this an enhancement request, we use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
