### ISSUE TITLE
Vault not locking correctly when locking the PC

### ISSUE THREAD

**Issue by albertopasqualetto** [bitwarden/desktop#677]
## Describe the Bug

If I lock the pc (for example with win+L) it should lock the vault if the setting is set to "when the system is inactive" because if the pc is locked, it is not active. In fact it only locks if I set to "when the system is locked".

## Steps To Reproduce

1. Go to Settings
2. Click on Vault timeout
3. Click on When the system is inactive
4. Lock the PC
5. Unlock and see that the vault is not locked

## Expected Result

The vault should be locked.

## Actual Result

The vault is not locked

## Environment

- Operating system: Windows 10
- Build Version (go to "Settings" → "About"): 20H2

## Comment

Sorry for the inaccurate translation of settings strings but my system is not set in English.
Anyway the issue should be easy to understand.

**Comment by Hinton** [comment]
The English phrasing is: "On System Idle".

I believe there's a confusion around exactly what "idle" means, in the Desktop application it will lock after 5min of system inactivity i.e. no user input. Locking the desktop doesn't trigger this.

There are an existing feature requests for adding multiple timeout options, https://community.bitwarden.com/t/chrome-extension-allow-multiple-timeout-options/18643 which I believe would be an appropriate solution. Since we use the forums to track feature requests I'm going to close this issues for now.
