### ISSUE TITLE
Wildcard Search doesn't work anymore after updating the desktop client

### ISSUE THREAD

**Issue by emorinaj** [bitwarden/desktop#679]

**Comment by cscharf** [comment]
Currently working on reproduction steps and validation so we can get this resolved. @emorinaj , did you haver any additional detail you can provide?

**Comment by bazzik** [comment]
@cscharf
What exactly you need (info etc).

I can describe my issue.

**The search stopped working everywhere where I use Bitwarden: Firefox extension, Google Chrome extension, Brave browser extension, Desktop app.** Happen with last last update (since Sunday... or was it Saturday?)

I have quite a few logins where in Notes section I did put some comment that starts with `#TODO ` and have Secure Notes where the title starts with the same `#TODO` For example:
```
#TODO Change password to a more secure one
```
```
#TODO Change email account to xxx
Current email: yyy
```
```
#TODO Change email to xxx; or perhaps just delete this account
```
```
#TODO Setup monthly backups 
```

Right now it only finds Secure Notes (because it's in the record title) but before the recent update it was also finding over 20 Logins where that text was present in the Notes.

The same with `2FA` as a text: I have over 10 logins where I have stated that this login has OTP 2FA set up:
```
2FA setup with OTP app code
```
```
2020-06-22: Set up 2FA (my personal phone no)
```
For these it finds only 4 entries, but it should be at least 7 or 8 more.

-----

Another example: sadly Bitwarden has no support of tags or categories. Therefore for ALL of my work related logins I've added custom field named "Tags" and as a value I'm using hastags, for example:
```
#work #amazon #2fa
```
```
#work #project2 #ios
```
I have more than 100 logins where `#work` is used .. and right now search for `#work` returns no results at all (it does not matter where the search term will be: at the begging of the value (like `#work` is) or in the middle/at the end (like `#2fa`)).

**Comment by cscharf** [comment]
thanks @bazzik , will be resolved with:
* https://github.com/bitwarden/jslib/pull/251
* https://github.com/bitwarden/desktop/pull/683
* https://github.com/bitwarden/web/pull/810
* https://github.com/bitwarden/cli/pull/219
* and https://github.com/bitwarden/browser/pull/1569

**Comment by emorinaj** [comment]
Thanks for the fast fix! 👍
