### ISSUE TITLE
Global keyboard shortcut to bring Bitwarden to front?

### ISSUE THREAD

**Issue by bcosynot** [bitwarden/desktop#68]
Hi, are you planning on implementing a global keyboard shortcut to bring Bitwarden to the front? For instance LastPass on macOS has Command+Shift+L to do that.

**Comment by kspearrin** [comment]
We are no longer handling feature requests here as GitHub issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
