### ISSUE TITLE
Search Vault won't work if I type only one character

### ISSUE THREAD

**Issue by mnjihw** [bitwarden/desktop#689]
## Describe the Bug
Nothing happens if I type only one character into the Search Vault textbox.

## Steps To Reproduce
Type only one letter into the Search Vault.

## Expected Result
Vault list is filtered according to the value entered into the Search Value textbox.

## Actual Result
Nothing happens.

## Environment
- Operating system: Windows 10 Home
- Build Version: 19042.746

**Comment by cscharf** [comment]
Hi @mnjihw , this is by design. If you would like to advocate for a change in this behavior you may do so by opening an enhancement request in our [community forum](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
