### ISSUE TITLE
Secure Note RTF formatting possible? Seems to be just txt formatting

### ISSUE THREAD

**Issue by lalicatala** [bitwarden/desktop#698]
## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina] Mac 0s 10.13.6
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10] latest build

**Comment by Greenderella** [comment]
No RTF formatting is available at the moment. 

The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.
