### ISSUE TITLE
[Windows] keytar.node not found in app.asar

### ISSUE THREAD

**Issue by Igetin** [bitwarden/desktop#70]
When attempting to launch the program, the following error message is shown. This happens on Windows 8.1, and affects both the installable and the portable version of Bitwarden (version 1.0.5).

![image](https://user-images.githubusercontent.com/14016863/37371926-c6a602c0-2719-11e8-8cac-1d85f516d792.png)

<details>
 <summary>The same message as text</summary>

```
Uncaught Exception:
Error: ENOENT, node_modules\keytar\build\Release\keytar.node not found in H:\Softa\bitwarden\resources\app.asar
    at notFoundError (ELECTRON_ASAR.js:114:19)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:9)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (H:\Softa\bitwarden\resources\app.asar\node_modules\keytar\lib\keytar.js:1:169)
    at Object.<anonymous> (H:\Softa\bitwarden\resources\app.asar\node_modules\keytar\lib\keytar.js:61:3)
    at Module,compile (module.js:569:30) 
```
</details>

**Comment by kspearrin** [comment]
Honestly I am not sure. This is the library we use to access the Windows credential store.

**Comment by Igetin** [comment]
Looks like this is an unsolved problem in asar: https://github.com/electron/asar/issues/115

**Comment by vladimiry** [comment]
I guess [unpacking](https://github.com/vladimiry/email-securely-app/blob/37a307f2f8184e287564041b97207826077e3101/electron-builder.yml#L32) keytar module might be a workaround. I unpack all the modules with native dependencies for another original reason though.

**Comment by kspearrin** [comment]
Someone recently contacted us about this issue and said they resolved it by disabling Windows Defender and then later whitelisting the Bitwarden app from it. Maybe it's something antivirus is blocking?

**Comment by vladimiry** [comment]
Electron unpacks native dependencies in order to execute/use them (such as keytar). That's why shipping such dependencies pre-unpacked solves the issue. `electron-builder` supports unpacking out of the box, as shown in my previous message.
It's very likely that antivirus-like software will detect unpacking and running executables as a potentially dangerous activity. The thing is that Electron unpacks native dependencies with random name, so it might be tricky to whitelist them, but not when you ship native dependencies pre-unpacked since in this case, executables get constant names.
