### ISSUE TITLE
 Option Needed: Disable auto update

### ISSUE THREAD

**Issue by shmaiz** [bitwarden/desktop#731]
- Operating system:  Linux Mint
- Build Version: 1.24.6

Hello and good day to you.

Bitwarden.AppImage is running in the backroung on a system with very tight storage [1GB free storage].
The auto update sometimes fills available storage and I get a storage warning.
Moreover, this is happening on a business machine [Database] with very slow internet [Living in Yemen].

Please give the user the choice to disable auto updating in the background.

Thank you very much.

**Comment by kendratodd** [comment]
Hi @shmaiz, thank you for the feedback! 

It looks as though we have a few open requests in our [community forum](https://community.bitwarden.com/search?q=auto%20update%20category%3A5) that are similar to this enhancement. Please feel free to sign up for the community forum so that you can upvote or add any additional details that will help promote your ask. 

This issue will now be closed. Thanks!
