### ISSUE TITLE
The app does not finish loading after installation

### ISSUE THREAD

**Issue by CaptainCustard** [bitwarden/desktop#747]
## Describe the Bug

I downloaded the app from the App Store and launched it. The app screen starts loading and it keeps on forever. I attached a screenshot.

## Steps to Reproduce

1. Download the app from the App Store.
2. Launch the app.

## Expected Result

The app to load for a little bit then starts working.

## Actual Result

The app keeps loading.

## Screenshots or Videos

<img width="1062" alt="Screen Shot 2021-03-03 at 12 10 09 PM" src="https://user-images.githubusercontent.com/56449814/109851956-dedd3e00-7c19-11eb-875a-d24b25036e2a.png">

## Environment

- Operating system: macOS 11.2.2
- Build Version (go to "Settings" → "About"): I can't see this as the app never finish loading.

**Comment by exprez135** [comment]
I'm also experiencing this problem. Only on the version downloaded from the App Store (which seems to be 1.24.5 instead of the current 1.24.6. Attached is log file showing the one error I'm getting in Developer Tools console.
[-1615001593020.log](https://github.com/bitwarden/desktop/files/6094617/-1615001593020.log)

**Comment by kendratodd** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
