### ISSUE TITLE
Fails to update

### ISSUE THREAD

**Issue by alanb1954** [bitwarden/desktop#772]
when trying to update, it fails with the message SNAP BITWARDEN not available

**Comment by kendratodd** [comment]
Hi there @alanb1954! 

Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
