### ISSUE TITLE
Can't deny Bitwarden wants to use your confidential information Mac

### ISSUE THREAD

**Issue by Abdallatif** [bitwarden/desktop#800]
## Describe the Bug

Bitwarden keeps asking for confidential information even if I deny.

## Steps To Reproduce

1. Open Bitwarden app on mac.
2. Bitwarden will ask for access to confidential information
3. Deny permission.
4. The same popup will show again.

## Expected Result

Bitwarden should ask for access only once.

## Actual Result

Bitwarden keeps asking for permission

## Screenshots or Videos

<img width="340" alt="IMG_5602" src="https://user-images.githubusercontent.com/10572734/111815194-0dc70580-88e4-11eb-8967-b2a6b24ce9db.png">

## Environment

- Operating system: Mac OS Big Sur
- Installation method: Mac App Store
- Build Version 1.25.0 (516)

## Additional Context

Why does it needs access to the keychain?

**Comment by HVR88** [comment]
This is likely where it's going to save your userID so you don't have to type it every time you open Bitwarden.

**Comment by BeyondEvil** [comment]
I have this issue too.

Makes Bitwarden 100% unusable.

- Can't deny
- Asks for a password I have zero memory about setting. My Master Password does not work, and neither does my keychain password

Brand new M1 Mac Pro.

**Comment by eliykat** [comment]
We use the system keychain to store certain sensitive information, e.g. your decryption key if you set your Timeout options to "Never" or if you use biometric authentication.

I suspect that the reason the prompt keeps appearing is that we check the keychain regularly for various bits of data. If you haven't clicked Always Allow, it will be asking for your permission each time Bitwarden checks the keychain, and you'll get a constant stream of popups. (Even if you don't use one of these features, we may need to check the keychain to figure that out.)

The original bug report says:

> ## Expected Result
> Bitwarden should ask for access only once.
> ## Actual Result
> Bitwarden keeps asking for permission

This is a system dialog that we don't have control over. If you only want it to ask for permission once, you should click Always Allow. (Your keychain may also ask you to reauthenticate sometimes as explained [here](https://support.apple.com/en-au/guide/keychain-access/kyca1242/mac), but again that's not something we control.)

@BeyondEvil is correct that this should be your Mac's login password.

Hope this helps, I'll close this because there's not much we can do about it, but let me know if you have any questions.

**Comment by junderw** [comment]
@eliykat Perhaps we could put up a UI popup before querying the keychain for the first time.

It could say "Please unlock the Keychain with your Mac login password and click "Always Allow""

Then once they click OK, then query Keychain causing the popup.

Lots of smartphone apps do similar things today.
