### ISSUE TITLE
Desktop App window shows up on OS login before minimizing itself to tray icon

### ISSUE THREAD

**Issue by timurlenk07** [bitwarden/desktop#831]
## Describe the Bug

On Ubuntu 20.04 LTS, when logging in, while the Bitwarden Desktop app has settings "Launch on tray icon" and "Automatic launch on login" enabled, the app window shows for a second before minimizing itself to the tray. (The actual setting labels might be slightly different as I have Hungarian language setup.)

## Steps To Reproduce

1. Set "Launch on tray icon" and "Automatic launch on login" in settings
2. Restart the system and log in to the OS

## Expected Result

Bitwarden icon shows up on tray **without** its window showing up.

## Actual Result

Bitwarden desktop app window shows up, then minimizes itself to the tray icon.

## Environment

- Operating system: Ubuntu 20.04 LTS
- Installation method: Snap
- Build Version 1.25.1

**Comment by hwittenborn** [comment]
I'm actually experiencing something a bit different, with the window __not__ disappearing, even with the settings you mentioned turned on.

The window, for whatever reason, contains my boot vendors logo in part of the window (I have auto-login turned on if that relates at all), and can't be closed unless I click `Show / Hide` in the Bitwarden system tray icon first (attempting to hit `X` will do nothing otherwise):

![Screenshot from 2021-06-04 23-59-38](https://user-images.githubusercontent.com/74838472/120880851-75f7c000-c592-11eb-8458-0a5b84297407.png)

I'm using the Debian (.deb) release though, more specifically the [AUR build](https://aur.archlinux.org/packages/bitwarden-bin/) (though I'm actually *running* it on Ubuntu 20.04, so any issues shouldn't really be from the AUR build, unless in the file copying, as it just pulls the deb).

I've reported a similar issue in https://github.com/vector-im/element-web/issues/17033 as well, and I wouldn't doubt if this is just an issue with electron or something.
