### ISSUE TITLE
Locking the vault stops the clear clipboard timer

### ISSUE THREAD

**Issue by ghost** [bitwarden/desktop#857]
Desktop App on Windows 10 does not automatically delete copied values from the clipboard (if option set).

**Comment by SergeantConfused** [comment]
Hi there,

I've tested this on two machines running Windows 10 Pro with Bitwarden desktop client version 1.25.1, and the values got cleared from the clipboard after 10 seconds. Please uninstall your client, clear out leftover data: https://bitwarden.com/help/article/data-storage/, reboot, reinstall, and let me know if that changes anything.
Also, please make sure that Clipboard History is not active in your operating system: https://support.microsoft.com/en-us/windows/clipboard-in-windows-10-c436501e-985d-1c8d-97ea-fe46ddf338c6

I thank you in advance for your understanding and cooperation,

**Comment by marcoingr** [comment]
Hi there,

I finally understood the problem: you must not lock the vault before the copied values are deleted from the clipboard, otherwise they will not be deleted (I only tried with the deletion set to 10 seconds, operating system Windows 10 HOME - 64 bit, Bitwarden Desktop App version 1.25.1).
I don't know if this can be called a bug and certainly from now on I will wait a little longer before locking the vault, but I believe such a thing shouldn't happen at all.

Thanks again

**Comment by eliykat** [comment]
I think we can classify this as a bug, the expected behaviour should be either:
* if a clear clipboard timeout is set, that timeout should continue to run even if the vault is locked or logged out
* if a clear clipboard timeout is set, it should immediately timeout when the vault is locked or logged out

**Comment by marcoingr** [comment]
Hi there,
unfortunately we have the exact same problem also for mobile: I tried with iOS 14.4.2 (iPhone SE old model 2016-2017), Bitwarden App vers. 2.9.1, clipboard clearing set to 30 seconds and the problem persists.
I have not done and do not have the possibility to do further tests on other devices, but at this point it seems to me very likely that the problem is spread across all products.
Thanks
