### ISSUE TITLE
Copy password feature not copying the correct password 

### ISSUE THREAD

**Issue by stonemic2293** [bitwarden/desktop#863]
When copying password from Win 10 app, it copies weird urls.

Open app
Search Microsoft
RightClick on entry
Copy password

4. Click on '...'

Copy the correct password to the clipboard 

## Screenshots or Videos

Windows 10
Downloaded from Bitwarden.com
1.25.1

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Installation method: [e.g. Downloaded from Bitwarden.com, Mac App Store / Microsoft Store, Homebrew, Snap] 
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]

**Comment by eliykat** [comment]
Can you please provide an example of the correct password vs. what's copied to clipboard? (Please use a fake password so you're not exposing any confidential information.)

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
