### ISSUE TITLE
Search should also search in Passwords

### ISSUE THREAD

**Issue by rggjan** [bitwarden/desktop#87]
I (and I assume many others) used the same password for many websites in the past. It would be useful to search for passwords (or parts of passwords) that appear in multiple entries, to see what sites use the same password.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by rggjan** [comment]
Ok, sorry! Thought this was sufficiently close to a bug, but I'll append it here then: https://community.bitwarden.com/t/advanced-vault-searching/36/8

Thanks for the fast response!
