### ISSUE TITLE
Doesn't auto startup on windows load.

### ISSUE THREAD

**Issue by JoTesla** [bitwarden/desktop#880]
## Describe the Bug
Hello guys,
I have Windows 10 Pro. Recently I installed Bitwarden and the feature autostart doesn't works even if I run the app as admin and recheck the box.

## Steps To Reproduce

Just install it and no startup on windows load.

## Expected Result
 

Startup

## Environment

- Operating system: Windows 10 Pro 20H2
- Installation method: [Downloaded from Microsoft Store] 
- Build Version:
Версия 1.25.1
Shell 11.3.0
Renderer 87.0.4280.141
Node 12.18.3
Architecture ia32

**Comment by Ruffythemonkey** [comment]
many store apps do not support autostart. This is due to Microsoft's rstrictions.
Install the normal Desktop App with Setup.

**Comment by JoTesla** [comment]
If it's impossible to integrate autostart, imho is better to hide this option from the settings to prevent users from confusing.

**Comment by o-l-a-v** [comment]
A workaround I've done with other Microsoft Store apps, is adding their shortcut to the good old start menu folder "Startup".

**Comment by eliykat** [comment]
Hi @JoTesla, we've been unable to reproduce this bug. Please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. They'll help you configure and troubleshoot this, and if they're able to reproduce it as a bug, I'll reopen this thread with the additional information they provide.

You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
