### ISSUE TITLE
BW autodelete trash after 30 without asking user!

### ISSUE THREAD

**Issue by MustachedMario** [bitwarden/desktop#895]
## Describe the Bug
Bitwarden AUTOdeletes trash after 30 days without asking the user or provide an option to turn this off!

## Steps To Reproduce
Wait 30 days and bitwarden deletes **UNASK** all data in trash!

## Expected Result
Ask the user to delete any items, even there is in trash!
Provide an option to prevent this ridiculous behavoiur!

## Environment
Any platform

## Additional Context
**THIS IS MY DATA, THE TRASH ALSO! IT'S MINE, NOT YOURS DAMIT!**
YOU DON'T HAVE THE RIGHT TO DELETE ANY USER DATA!

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
