### ISSUE TITLE
Eternal spinning wheel on startup

### ISSUE THREAD

**Issue by alaingad** [bitwarden/desktop#917]
After the last 2 updates when starting BitWarden i get an eternal spinning wheel. 
The only way of making it go away is to click on All Items

## Describe the Bug

After the last 2 updates when starting BitWarden I get an eternal spinning wheel. 
The only way of making it go away is to click on All Items-->

Start the software

## Environment
Edition	Windows 10 Home
Version	20H2
Installed on	‎1/‎6/‎2021
OS build	19042.985
Experience	Windows Feature Experience Pack 120.2212.2020.0

Updates from BitWarden

- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]
Version 1.26.4
Shell 11.3.0
Renderer 87.0.4280.141
Node 12.18.3
Architecture x64

**Comment by mwalbeck** [comment]
You should try the steps explained here: https://github.com/bitwarden/desktop/issues/894#issuecomment-843641498

With the 1.26.4 update the underlying issue was fixed but it seems it is still present until you clear out the entry in the data.json file. After clearing that line the desktop client is back to normal for me.

**Comment by alaingad** [comment]
That has fixed the issue for me.

Thanks for the great service.
