### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by i-panov** [bitwarden/desktop#93]
Hi there, I'm very pleased with the appearance of the desktop application. Finally, I can use Bitwarden! After a short introduction to the application, questions arose:

1. How about folding into a tray? This is a standard feature for all password managers. Because it is impossible to keep it open all the time.

2. What about the pin-code entry? Also a standard function. It's not very convenient to enter a long master password all the time. It would be optimal to be able to enter the pin code while the PC is turned on. And after rebooting or going into hibernation mode - the first input is again on the password.

3. I would like to synchronize between the application and the browser extension. To not enter the password in the extension if it has already entered the application and vice versa.

4. In the password generator there is no possibility of generating a passphrase (as in Enpass for example). By the way, this is not in the browser extension and in the mobile application, either. Please add this! It would be very useful!

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
