### ISSUE TITLE
Hierarchical collections cause indefinite loading on Desktop App.

### ISSUE THREAD

**Issue by Sc07713** [bitwarden/desktop#933]
Hi There,

My organisation has some complex hierarchical collections e.g. SupportTeam/Name/ServerGroup/NamedUserLogin

For some reason on the desktop this doesnt seem to load anymore. It used to about a week ago, now it is failing.
Perhaps I need to reset something, I have tried reloading, but that doesnt seem to help.

If you can make a fix for this type of issue that would be great, but if you have a user work around for the time being that could be useful too.

![image](https://user-images.githubusercontent.com/17331183/120322545-dcc57100-c327-11eb-9484-7b51bc81ca7d.png)

**Comment by joeczucha** [comment]
Also seeing this, glad it's not just me :) works fine on web and in browser plugin

**Comment by kapitainsky** [comment]
maybe this sheds some light on possible temporary solution:

https://github.com/bitwarden/desktop/issues/894#issuecomment-843641498

**Comment by joeczucha** [comment]
Well, that worked for me. Thanks @kapitainsky

**Comment by eliykat** [comment]
This could either be:
* #894 as @kapitainsky said - this can be fixed by upgrading to the latest desktop version. You may have to follow the instructions in that comment just once after the upgrade to reset your local data, after that the problem should be resolved.
* #934 - you could check whether this is the same error by checking the devtools console (View > Toggle Developer Tools > console) and comparing it to what's reported in that issue.

@Sc07713 can you please let me know how you go and close this if this fixes the issue or it's a duplicate.

**Comment by eliykat** [comment]
Hi @Sc07713, I haven't heard back from you, so I'll close this issue. If it continues to be a problem and you don't think it's covered by the issues I linked above, please feel free to mention (@) me here and I'll reopen.

**Comment by Sc07713** [comment]
@eliykat  Yes the solution above, modifying the json seemed to work for me. It hasnt been a problem since. Thanks for your help.

**Comment by Sc07713** [comment]
@kapitainsky Thanks mate, fixed my problem. Really appreciate the help.
