### ISSUE TITLE
Unable to download application package (7z) during installation

### ISSUE THREAD

**Issue by Najca** [bitwarden/desktop#95]
I have tried to install the desktop app multiple times but i get the same error every time
![bitwarden-installer-1 2 0 2 _2018-05-31_19-16-26](https://user-images.githubusercontent.com/3587562/40797250-cd89ae94-6507-11e8-936f-5abd6567512d.png)

Followed by this when I click cancel
![bitwarden-installer-1 2 0 2 _2018-05-31_19-16-36](https://user-images.githubusercontent.com/3587562/40797275-de4e2142-6507-11e8-8f60-acb1476c3bb2.png)

The only other post I have seen about this is a [closed issue from the 15th of March](https://github.com/bitwarden/desktop/issues/71) that was resolved by "downloading the package manually," but I have no clue on how to do that

**Comment by kspearrin** [comment]
1. Download the 7z package from the release page here: https://github.com/bitwarden/desktop/releases

You want this one by the looks of your error message: https://github.com/bitwarden/desktop/releases/download/v1.2.0/bitwarden-1.2.0-x64.nsis.7z

2. Place the 7z file in the same directory has the installer.

3. Run the installer again.

It will use the locally downloaded package instead of trying to download it itself.

**Comment by Najca** [comment]
That solved it! Thanks!
