### ISSUE TITLE
New releases and "Bug fixes"

### ISSUE THREAD

**Issue by kapitainsky** [bitwarden/desktop#985]
You maintain BW source code as open source and it is something extremely positive. But I have a feeling that you try for no reason to keep "secrecy" of what has been fixed with every new release.

"Bug fixes" comment accompanying every new release sounds like from close source software company reassuring users that they are working. Yes one can get through commits and figure out what changed or been fixed but it would be beneficial I think for everybody if release comments were more detailed. If I see that feature X has been fixed maybe I will have a chance to check and report back if something is still wrong.

At the moment I can install new version and just hope that maybe bug fix I was waiting for was fixed or not.

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and similar development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing [feature requests](https://community.bitwarden.com/c/feature-requests) like this one. (I know you're not asking for a change to the software, it's more about our releases processes, but the community forums is still the best place for this.)

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
