### ISSUE TITLE
Windows Store version out of date?

### ISSUE THREAD

**Issue by NPadrutt** [bitwarden/desktop#986]
Hi!

I noticed, that the store version of bitwarden is several version behind as it seems. I'm on version 1.26.3 and in the release page it shows 4 new releases. Also on the bitwarden website the store version seems to be gone and only the direct download left. Is the store version no longer supported or is there just something that has to be resolved first before a new update for the store can be made? 

EDIT: I actually found the store download option in the more section. But that would still leave the question for the version discrepancy.

**Comment by eliykat** [comment]
We've submitted the latest version to the Microsoft Store. It'll be subject to review by Microsoft which may cause some delays - hopefully no more than a couple of weeks, but that's out of our control. Hopefully you'll see an updated version there soon.

**Comment by NPadrutt** [comment]
@eliykat the update already made it through, thank you! Will future updates follow automatically or is that a manual process to submit those? Meaning would it make sense to switch away from the store version if it is important for one to have the latest version in a timely manner?

**Comment by eliykat** [comment]
It's not automated like the MacOS store is (I assume for some good devops reason), however we've added it to our release checklists to make sure it's not missed. Ideally the only delay should be the one caused by Microsoft verification (~1 week?), but if that's too much of a lag for you then you could switch to a different release channel. I personally installed from the Windows installer downloaded from our website, that has an auto-update feature that has worked well for me in the past.
