### ISSUE TITLE
Renaming a vault folder with children folders breaks folder tree

### ISSUE THREAD

**Issue by devilcrayon** [bitwarden/desktop#994]
## Steps To Reproduce

1. Create a folder in password vault such as 'Archive'
2. Create sub-folders in the folder created above, such as 'Folder1' and 'Folder2'. These will have a path of `Archive/Folder1' and 'Archive/Folder2'
3. Click on the 'edit' pencil on the top level folder and change the name -- 'Archive' to 'IgnoreMe'

## Expected Result

The top level folder name changes and the sub-folders remain as sub-folders of the new name.  

## Actual Result

The top level folder is renamed, but the pathing for the sub-folders keeps the original name, orphaning them until their path is edited to have the same top-level folder name. Using the example above, 'Archive' changes to 'IgnoreMe', but now there are 'Archive/Folder1' and 'Archive/Folder2' shown in the vault tree.

## Environment

- Operating system: [Windows 10]
- Installation method: [e.g. Downloaded from Bitwarden.com] 
- Build Version (go to "Settings" → "About"): [1,27.1]

**Comment by Greenderella** [comment]
Hi @devilcrayon, 
 
This is the expected behavior. Folders and their sub-folders aren’t parent-child, they are not related or inherit any characteristics between them and serve only a visual/organizational purpose. You will need to recreate the folder tree if the name of the _root_ folder gets changed.
​
Let us know if there is anything else we can do for you.

Kind regards,
Alex
