### ISSUE TITLE
small personal suggestion : Ctrl Q

### ISSUE THREAD

**Issue by opqriu** [bitwarden/desktop#996]
Debian + Flatpak and Appimage Use

I use a setting to minimize to tray icon instead of quit when app closes. 

In this case, even if I press Ctrl Q, I would like it to be minimized to the tray icon instead of quit. 

It's cumbersome to press Ctrl Shift M or the X button with the mouse.

Most apps are already
With the minimize to tray icon on close setting enabled,
Pressing Ctrl Q will minimize it to the tray icon instead of completely shutting it down.
Bitwarden doesn't, so it's uncomfortable

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one. (There's an existing feature request thread for keyboard shortcuts [here](https://community.bitwarden.com/t/add-essential-keyboard-shortcuts-navigation/76).)

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
